### ISSUE TITLE
Minor Cosmetic Information & Updates for NAS

### ISSUE THREAD

**Issue by s1mwest** [publicarray/spksrc#14]
Hey, could I check this please?

Package Center in Synology DSM 6.2.3 shows conflicting information as follows:

Installed version: 2.0.42-5
Newest online version: 2.0.33-4
The publisher is 'SynoCommunity' and the link in Package Center takes me to synocommunity.com where I see the 2.0.33-4 version.

Up until recently I was updating the package manually by downloading from Github,, but the last update automatically showed in Package Center on both of my NAS devices - great 👍.  Since then I see further updates on GitHub, but not for my platforms.

Have I misunderstood or incorrectly configured something?  Or do I just need to be patient for the spksrc releases? :)

May I say a huge thank to you for this project/product.  I've been using it very happily and effectively for some time (I assisted jedisct1 when I first set it up, to test the blacklist update process which was failing on my devices).  Since he remedied everything, I have sworn by it in all my environments.

**Comment by publicarray** [comment]
Hi! @s1mwest,

It's not a bug :)

So the version on github here are build more for development & testing and will usually be more recent. I just haven't send a Pull Request to SynoCommunity yet. It's been a while so I'll get to it soon. 

What platform are you using? I made changes to how packages are build with Github actions and used the newer generic builds.

Thank you for helping to Encrypt DNS!

**Comment by s1mwest** [comment]
Hi @publicarray thanks!

Ah I see.  I'm learning more about how GitHub works now, thus your comments regarding a pull request and actions clicked!  I'm no developer - I just try to put things together :)

So my platforms are Intel Celeron (I guess that's x64) and Armada 375
