### ISSUE TITLE
jellyfin-plugin-how to install plugin?

### ISSUE THREAD

**Issue by hiair2323** [publicarray/spksrc#17]
i want install plugin
https://github.com/Libitum/jellyfin-plugin-douban
i set /var/config/plugins in nas. but it not install
how to install plugins ?

**Comment by publicarray** [comment]
Did you try and add Douban as a repository as described in their [readme](https://github.com/Libitum/jellyfin-plugin-douban#2-usage)? `https://raw.githubusercontent.com/Libitum/jellyfin-plugin-douban/master/manifest.json`

Manual install:

```sh
$ ssh nas
$ sudo su
$ cd /var/packages/jellyfin/target/var/data/plugins
$ mkdir douban && cd douban
$ wget https://github.com/Libitum/jellyfin-plugin-douban/releases/download/v1.0.0/Jellyfin.Plugin.Douban.zip
$ 7z x Jellyfin.Plugin.Douban.zip
$ chown -R sc-jellyfin:jellyfin .
$ rm *.zip
```

You must restart Jellyfin from the Package Center to load the plug-in.

**Comment by hiair2323** [comment]
tks it is work
