### ISSUE TITLE
Jackett-dotnet release cannot update itself

### ISSUE THREAD

**Issue by AnonTester** [publicarray/spksrc#22]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ jacket-dotnet
_Package Version:_ 0.16.1583-11

_NAS Model:_ Synology DS414
_NAS Architecture:_ arm7
_DSM version:_ DSM 6.2.3-25426 Update 2

### Expected behavior
Jacket updates itself automatically and/or when check for update triggered manually

### Actual behavior
No update, version number in the footer lists 0.0.0.0, message in log says "Skipping checking for new releases because Jackett is runing in IDE."

### Steps to reproduce
_1._ Install jackett-dotnet_armv7-6.1_0.16.1583-11.spk manually via DSM
_2._ Open web interface of jackett
_3._ Click on "Check for updates", then "View logs"

#### Other logs
```
2020-10-10 15:40:54 | Info | Skipping checking for new releases because Jackett is runing in IDE.
-- | -- | --
2020-10-10 15:40:54 | Info | Checking for updates... Jackett variant: CoreLinuxArm32
```

**Comment by AnonTester** [comment]
Let me also thank you very much for creating the dotnet package in the first place and submitting it to the synocommunity repo! I hope it'll be merged soon and with that get rid of the mono requirement and regular issues with mono.

**Comment by publicarray** [comment]
Thank you for the report It's fixed in 6ee07544c9493a2fae3eec3b7da2668b39a8cf10, I'll push a new release soon

**Comment by AnonTester** [comment]
I can confirm the version number after installation is correct and updating works. Thank you!

**Comment by publicarray** [comment]
Thank you for confirming 😄
