### ISSUE TITLE
jellyfin 

### ISSUE THREAD

**Issue by jinfeng1985** [publicarray/spksrc#26]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ jellyfin_x64-7.0_10.6.4-1
_Package Version:_ 7.0_10.6.4-1

NAS Model: synology
NAS Architecture: 920+
DSM version: 7.0

The vast majority of 4K movies can not run, as shown in the figure
Does DSM920 + not support 4K transcoding

![1](https://user-images.githubusercontent.com/22148953/104274258-62609580-54db-11eb-9613-70063ce20f3f.jpg)
![2](https://user-images.githubusercontent.com/22148953/104274288-6db3c100-54db-11eb-8982-d7947959bc34.jpg)
![3](https://user-images.githubusercontent.com/22148953/104274302-71474800-54db-11eb-867a-33bd03c4f6a5.jpg)

**Comment by publicarray** [comment]
From the [Spreadhseet] from plex :(https://docs.google.com/spreadsheets/d/1MfYoJkiwSqCXg8cm5-Ac4oOLPRtCkgUxU0jdj3tmMPc/edit#gid=1274624273) The DS920+ 

> * Supports decoding  2160p H.264 SDR (8-bit - Main - bt709 colorspace)
Encoding is limited to 1080p output
> * Supports decoding 4K HEVC (H.265) & 4K H.264 SDR (8-bit)
Encoding is limited to 1080p output

Can you look at transcode log files? Thanks

It's also possible that  the client doesn't have support: https://jellyfin.org/docs/general/clients/codec-support.html

**Comment by publicarray** [comment]
You can also change the playback settings to see if you can use "Direct Play"

**Comment by publicarray** [comment]
I suggest you ask someone from jellyfin/ jellyfin forum
