### ISSUE TITLE
When will jellyfin 1.8.0 version be updated on dsm?

### ISSUE THREAD

**Issue by stevenliuit** [publicarray/spksrc#33]
When will jellyfin 1.8.0 version be updated on dsm?

**Comment by publicarray** [comment]
I don't think you are on version 1.8.0 did you mean the beta 10.8.0? FYI the package has moved to https://synocommunity.com/package/jellyfin which is v10.7.7-4 and is the latest stable, we don't publish beta versions.

**Comment by publicarray** [comment]
Answered in https://github.com/SynoCommunity/spksrc/issues/5231
