### ISSUE TITLE
Update DNSCrypt-Proxy to 2.0.22

### ISSUE THREAD

**Issue by kc6108** [publicarray/spksrc#7]
Please see https://github.com/SynoCommunity/spksrc/issues/3694

**Comment by publicarray** [comment]
Thanks for reminding me! I will package it on my repo asap.

**Comment by publicarray** [comment]
I've published a new release: https://github.com/publicarray/spksrc/releases/tag/dnscrypt-proxy-2.0.22

fixed in 038740f2104583a0d6d1fffed921f4e8276e235b
